### ISSUE TITLE
Support MongoDB import from stdin

### ISSUE THREAD

**Issue by fabriceclementz** [Qovery/Replibyte#100]
As for MySQL and PostgreSQL, we want to add the possibility to import an existing mongodump.

Ex : 

```sh
cat mongo_dump/* | replibyte -c ./conf.yaml dump create  -i -s mongodb
```

**Comment by evoxmusic** [comment]
That would be great to be consistent with Postgres and MySQL

**Comment by fabriceclementz** [comment]
> That would be great to be consistent with Postgres and MySQL

@evoxmusic  I'm not sure to understand what do you mean by that, maybe I've missed something ? Anyway, it's better that we stay consistent as much as possible between the different sources.

**Comment by evoxmusic** [comment]
Sorry, I was not clear. I'm aligned 😁
