### ISSUE TITLE
Allow all supported ways for AWS authentication

### ISSUE THREAD

**Issue by vemilyus** [Qovery/Replibyte#102]
Hi there!

Why are you enforcing the use of the IAM access key ID and secret access key options? This is preventing us from using this tool effectively in an environment where you don't get those credentials by default (like EC2 with an instance profile).

The AWS SDK for Rust already supports all the various methods of authentication, so I don't see why access key id/secret access key pairs would be absolutely necessary.

https://github.com/Qovery/Replibyte/blob/67c84c34ad161d59d2a462a0686297f1c1b92f2c/replibyte/src/datastore/s3.rs#L53

From our understanding it is AWS best practice to offload the actual handling of credentials to the SDK and to use AWS configuration profiles if access to other accounts is required.

All the best,
Alex

**Comment by evoxmusic** [comment]
Hi Alex, thanks for pointing out best practices. I will take a look at what we can do to provide multiple ways to authenticate through AWS. If you have some time to provide a PR, it would be greatly appreciated :)

**Comment by vemilyus** [comment]
I've decided to implement this. 

However, this would include some changes to the AWS related YAML properties. Is that ok?

**Comment by evoxmusic** [comment]
Of course, no problem since it can help to improve AWS supports
