### ISSUE TITLE
Rename backup to dump?

### ISSUE THREAD

**Issue by fabriceclementz** [Qovery/Replibyte#108]
As we rename the cli command from backup to dump, I think we could rename it to Dump in the datastore directory. 
WDYT?

Example:

```rust
// datastore/mod.rs
pub struct Backup {
    pub directory_name: String,
    pub size: usize,
    pub created_at: u128,
    pub compressed: bool,
    pub encrypted: bool,
}
```

to

```rust
pub struct Dump {
    pub directory_name: String,
    pub size: usize,
    pub created_at: u128,
    pub compressed: bool,
    pub encrypted: bool,
}
```

```rust
// datastore/mod.rs
pub struct IndexFile {
    pub backups: Vec<Backup>,
}
```

to 

```rust
pub struct IndexFile {
    pub dumps: Vec<Dump>,
}
```

This update will lead to a renaming of the key `backups` to `dumps` inside the `metadata.json` file.

**Comment by evoxmusic** [comment]
Yes, it will be more consistent, however, it's a breaking change for the metadata.json. How should we manage it?

**Comment by fabriceclementz** [comment]
My first thoughts:

1. The simplest solution could be to add a warning that indicates to the user he must rename "backups" to "dumps" manually.

2. A more effective solution could be to add the replibyte version inside the metadata.json.
When running the CLI, we could compare the [replibyte version](https://docs.rs/clap/latest/clap/struct.App.html#method.get_version) with the version in the metadata.json and rename "backups" to "dumps", on top of that we must update the "version" in the metadata file. 

In the next run, we'll find the "good" version and do anything.

metadata.json now:

```json
{
  "backups": []
}
```

metadata.json after running with the new Replibyte version:

```json
{
  "v": "0.7.0",
  "dumps": []
}
```

As a prerequisite, this solution needs that we handle the replibyte version correctly when creating a new release, for this I suggest to create a bash script which takes the replibyte version to release as an argument and updates the Cargo.toml files and create a tag?

**Comment by evoxmusic** [comment]
LGTM - making the `metadata.json` file versioned is a good way to prevent breaking changes and update it smoothly from a lower version 👍🏽

**Comment by evoxmusic** [comment]
@fabriceclementz can we close this one?

**Comment by fabriceclementz** [comment]
I have not implemented this for now but I can make some progress on it this week-end @evoxmusic.

**Comment by fabriceclementz** [comment]
Hi @evoxmusic 
Thx for merging :) I've seen you created a 0.8.0 release but the version in cargo.toml file is not updated.
I think today you're creating the releases directly from the Github UI?

Could you try to create it using `./release.sh {old_version} {new_version}`, `old_version` must match the actual version present in the cargo.tom file so for example, for creating a 0.8.1 release now should be `./release.sh 0.7.3 0.8.1`, this script updates all the cargo.toml files and create a new branch named `release-v0.8.1` and give you the link to open a pull request so we can have the RepliByte version updated correctly in the binary ?

**Comment by evoxmusic** [comment]
Thx for the explanation @fabriceclementz . It's done now :)
