### ISSUE TITLE
Show the source database schema

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/Replibyte#109]
As a user, I need to know what tables and columns are available if I need to set up the transformers and subset. It will be super convenient to show the source database schema with a command.

```bash
replibyte -c conf.yaml source schema

|    table    |    column    | 
...
```

Then we can analyze the table structure with potentially sensitive data and relations between tables.

**Comment by diceride** [comment]
I'm working on this.

**Comment by timkrins** [comment]
I created myself a little Python script to give me a default configuration containing all the tables in my database.

https://gist.github.com/timkrins/ebfa00ce220439d7c3dbe2a309c1a426

It would certainly be handy to have this functionality built in.

**Comment by evoxmusic** [comment]
Awesome @timkrins - I will take a deeper look but from what I see it's easily portable. Do you have in mind the limitations of what you did?
