### ISSUE TITLE
Are transformers optional?

### ISSUE THREAD

**Issue by brett-anderson** [Qovery/Replibyte#119]
According to the examples, it's possible to create a dump with no transformers:
https://github.com/Qovery/Replibyte/blob/main/examples/source-postgres-with-no-transformers.yaml

However, while trying this config example, I get
```
thread 'main' panicked at 'bad config file format: Message("missing field `transformers`", Some(Pos { marker: Marker { index: 81, line: 4, col: 16 }, path: "source" }))', replibyte/src/main.rs:84:56
```
Seems like it is not optional?

**Comment by evoxmusic** [comment]
Indeed, Transformers must be optional. A workaround until it's fixed would be to set a transformer targeting a non-existent column.

**Comment by fabriceclementz** [comment]
I will fix that
