### ISSUE TITLE
Postgres dumps can't work with azure databases because the username contains an @

### ISSUE THREAD

**Issue by bonflintstone** [Qovery/Replibyte#120]
On azure the usernames of postgres databases are of the form `user@db-something`. Adding this to a connection uri leads to something like:
`postgres://user@db-something:password@azure-host:5432/project_production`
To make this work directly with `pg_dump` or `psql`, one has to escape the `@` in the username with percentage encoding, leading to an uri like:
`postgres://user%40db-something:password@azure-host:5432/project_production`
This actually works for psql etc.

But replibyte seems to handle uris a bit differently, it seems it is parsed and then passed as separate arguments to the `pg_dump` command. This leads to one of two cases:
When using percentage encoding, the uri parsing works fine; but because this is not used as part of an uri anymore the username is passed like `psql ... -U user%40db-something ...` which leads to azure complaining that it does not have the right form (since the percentage encoding is never decoded).

When actually using the `@` directly the parsing of the uri seems to fail, leading to the following error:
```
> RUST_BACKTRACE=full replibyte -c replibytes-conf.yaml dump create
⠂ [00:00:00] [------------------------------------------------------------] 0B/100.00MiB (0s)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', subset/src/postgres.rs:98:22
⠒ [00:00:00] [------------------------------------------------------------] 0B/100.00MiB (0s)
   0:        0x101babf12 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4cae82d438451481
   1:        0x101bd350b - core::fmt::write::hb68c3045179d0cad
   2:        0x101ba3a6e - std::io::Write::write_fmt::haf84c797e63d79f0
   3:        0x101bae830 - std::panicking::default_hook::{{closure}}::he18137441e51da1f
   4:        0x101bae516 - std::panicking::default_hook::ha3efe84526f027fa
   5:        0x101baef8d - std::panicking::rust_panic_with_hook::h429a7ddefa5f0258
   6:        0x101baec7a - std::panicking::begin_panic_handler::{{closure}}::h9b033a6b15b84a74
   7:        0x101bac3a7 - std::sys_common::backtrace::__rust_end_short_backtrace::hcdd3bec8e0e38aa6
   8:        0x101bae97a - _rust_begin_unwind
   9:        0x101c31b73 - core::panicking::panic_fmt::hf7d6e5207e013f69
  10:        0x101c31a57 - core::panicking::panic::hdb1992cacba5f03a
  11:        0x1015cd76d - subset::postgres::PostgresSubset::reference_rows::he4c1b76a19831714
  12:        0x100f2b634 - <subset::postgres::PostgresSubset as subset::Subset>::read::h126272ed55c90b79
  13:        0x100f13b33 - <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run::h66d803ffd9703b71
  14:        0x100ecb701 - replibyte::commands::dump::run::hc49159c97d03533f
  15:        0x100f6a745 - replibyte::main::h394afcb0d6593cf1
  16:        0x100fddea6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb97ce907e31ab8f4
  17:        0x100eb975c - std::rt::lang_start::{{closure}}::he756fc152ca8ef7e
  18:        0x101bab645 - std::rt::lang_start_internal::hef78d5782ed29805
  19:        0x100f952e9 - _main
```
I assume this is because of the way the uri is parsed, the two `@`s may be confusing the parser to assume everything from `password@...` onward is the port or something similar.

**Comment by evoxmusic** [comment]
Can you please add a description with a way to reproduce the issue?

**Comment by bonflintstone** [comment]
> Can you please add a description with a way to reproduce the issue?

Yes, sorry. I accidentally created it before I was done. I hope I have added all the information you may need, but let me know if there is more I can do. I looked at the code briefly, but since I don't know rust I don't think I can contribute substantially. 

I think perhaps a decent unit test for my use case would look something like:
```
    #[test]
    fn parse_postgres_connection_uri_with_db() {
        assert_eq!(
            parse_connection_uri("postgres://root@something:password@localhost:5432/db").unwrap(),
            ConnectionUri::Postgres(
                "localhost".to_string(),
                5432,
                "root@something".to_string(),
                "password".to_string(),
                "db".to_string(),
            ),
        )
    }
```
or, if it seems easier to support percentage escaping in the username because one could leave rusts internal uri parsing alone (would also lead to the same connection string being used for `psql` and in the configuration file):
```
    #[test]
    fn parse_postgres_connection_uri_with_db() {
        assert_eq!(
            parse_connection_uri("postgres://root%40something:password@localhost:5432/db").unwrap(),
            ConnectionUri::Postgres(
                "localhost".to_string(),
                5432,
                "root@something".to_string(),
                "password".to_string(),
                "db".to_string(),
            ),
        )
    }
```
(adapted from https://github.com/Qovery/Replibyte/blob/main/replibyte/src/config.rs#L612)

**Comment by bonflintstone** [comment]
Thanks for the quick fix! That was actually amazing.
