### ISSUE TITLE
How to skip or fix the "thread 'main' panicked at 'TokenizerError"

### ISSUE THREAD

**Issue by rampuikoy** [Qovery/Replibyte#124]
Now I'm facing with this issue at the beginning and cannot move on from this step. Please help!

`failing query: '
CREATE TABLE `external_account_transactions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `transaction_id` int(11) NOT NULL,
  `payment_id` varchar(45) NOT NULL,
  `payout_id` varchar(45) NOT NULL,
  `amount_allocated` decimal(10,0) DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='new table Rich S - store the details of already sync''d transactions (likely to change)';'
thread 'main' panicked at 'TokenizerError { message: "Unterminated string literal", line: 11, col: 15 }', dump-parser/src/mysql/mod.rs:697:13
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: dump_parser::mysql::get_tokens_from_query_str
   3: replibyte::source::mysql::read_and_transform::{{closure}}
   4: dump_parser::utils::list_sql_queries_from_dump_reader
   5: <replibyte::source::mysql::Mysql as replibyte::source::Source>::read
   6: <replibyte::tasks::full_dump::FullDumpTask<S> as replibyte::tasks::Task>::run
   7: replibyte::commands::dump::run
   8: replibyte::main`

**Comment by evoxmusic** [comment]
@rampuikoy can you give more details on how to reproduce the error?

Do you have:

1. a dump to share
2. the conf yaml you use
3. the command you ran

Thanks
