### ISSUE TITLE
MongoDB can not connect to shards or SSL Atlas

### ISSUE THREAD

**Issue by diceride** [Qovery/Replibyte#135]
The [MongoDB connection string URI](https://www.mongodb.com/docs/manual/reference/connection-string/) is a format that defines connections between applications and MongoDB instances. MongoDB utilities parse the connection string URI using the Golang [mongo-driver/x/mongo/driver/connstring](https://pkg.go.dev/go.mongodb.org/mongo-driver/x/mongo/driver/connstring) library.

**Observed behavior**

The connection string URI is parsed manually (`--username=`, `--password=`, `--host=`) instead of passing it on to the mongodump utility. This creates several problems.

- Users can not connect to a MongoDB replicated cluster, as the `--host` parameter expects a single node.
- Users can not connect to a MongoDB node that uses SSL, as the `--ssl` flag needs to be set.

**Expected behavior**

Pass the connection string URI to the mongodumb utility as is using the `uri=` parameter and do not parse the connection string URI manually.

**Comment by evoxmusic** [comment]
Hi @diceride , can you confirm it's all good for you?

**Comment by evoxmusic** [comment]
I close this issue - feel free to re-open it if it's not the case :)
