### ISSUE TITLE
Process Killed after random amount of time

### ISSUE THREAD

**Issue by betoflakes** [Qovery/Replibyte#151]
This is my command and killed after some time.

<img width="1063" alt="CleanShot 2022-06-02 at 16 05 15@2x" src="https://user-images.githubusercontent.com/1946702/171738278-de11ab69-58ed-4c1b-9687-bbbcdd433cd4.png">

**Comment by evoxmusic** [comment]
Hi @betoflakes , can you please give more details on your config.yaml and your replibyte version?

**Comment by evoxmusic** [comment]
Hi, please feel free to re-open it if it still happens and have more details. Thank you
