### ISSUE TITLE
Error on dump: "Unterminated string literal"

### ISSUE THREAD

**Issue by ederski** [Qovery/Replibyte#166]
Hi, I'm using replibyte with Postgres and GCP. When I run `replibyte dump create`, the script panics with the error:
> thread 'main' panicked at 'TokenizerError { message: "Unterminated string literal", line: 9, col: 64 }', dump-parser/src/postgres/mod.rs:761:13

I previously saw this issue before, but it was fixed here: https://github.com/Qovery/Replibyte/issues/94. I was able to create a dump after that, but now I'm seeing the error again.

Happy to provide the specific failing query over email!

**Comment by evoxmusic** [comment]
Hi @ederski , to be sure it's (or not) a regression, can you share with me the part of your dump that is failing here?

**Comment by ederski** [comment]
@evoxmusic Sent you a DM :)

**Comment by evoxmusic** [comment]
HI @ederski , I looked at your query failing and it is another query that is failing to be correctly parsed by our Tokenizer. I am going. to try to reproduce it and provide a fix. I keep you posted

**Comment by evoxmusic** [comment]
@ederski I dm'ed you on Discord :)

**Comment by evoxmusic** [comment]
Hi @ederski , I've tried today to reproduce the issue with the 2 queries that you shared to me and no luck. It's working perfectly fine. Can you try to create a full dump with synthetic data to reproduce the bug? There is probably a succession of special characters making leading to this TokenizerError :(

**Comment by evoxmusic** [comment]
Hi @ederski , please re-open this issue if you still have the problem with the latest version. Thank you
