### ISSUE TITLE
question, is it possible to specify the pg_dump version to use, eg via path 

### ISSUE THREAD

**Issue by DoctorOgg** [Qovery/Replibyte#183]
Just taking at look at this and ran into this issue, I have multiple versions of pg_dump installed, would it be possible to set this in the config?

thanks

```
command error: pg_dump: server version: 10.18; pg_dump version: 9.6.22
```

**Comment by evoxmusic** [comment]
I think you can refer to [this issue](https://github.com/Qovery/Replibyte/issues/206) for a solution https://github.com/Qovery/Replibyte/issues/206
