### ISSUE TITLE
Failing tests for pull requests from forked repositories

### ISSUE THREAD

**Issue by fabriceclementz** [Qovery/replibyte#19]
Hi  @evoxmusic 

I think I've found why tests are failing on pull requests, it's because secrets are not passed to the runner for security concerns.

See https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

There is this note :

> Note: With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

I propose to replace `${{ secrets.AWS_ACCESS_KEY_ID }}` and `${{ secrets.AWS_SECRET_ACCESS_KEY }}` directly by the MinIO credentials.

I don't know any other solution, what do you think ?

**Comment by evoxmusic** [comment]
It makes sense that the credentials are not passed via the env Vars for forks (luckily haha). We can use unwrap_or("minioadmin") to fallback on minio credentials I think
