### ISSUE TITLE
Utf8Error on dump create

### ISSUE THREAD

**Issue by charlyhue** [Qovery/Replibyte#220]
Database: **MariaDB**
Version: **10.5.15**
Character set: **Utf8mb4**

Command ```cat dump.sql | replibyte -c replibyte.yaml dump create -i -s mysql``` return this error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 950246712, error_len: Some(1) }', /root/src/dump-parser/src/utils.rs:74:70
```

Dump Command: 
```
mysqldump -h XXX -u XXX -p --add-drop-database --add-drop-table --skip-extended-insert --complete-insert --single-transaction --quick --column-statistics=0 --default-character-set=utf8mb4 db > dump.sql
```

- I tried dump with `--default-character-set=utf8` and i got the same error.
- I tried with and without transformer and i got the same error.

**Comment by evoxmusic** [comment]
Hi @charlyhue , what's your operating system?

**Comment by charlyhue** [comment]
Hi @evoxmusic I'm on Macos 12.15.1 (arm).

**Comment by charlyhue** [comment]
Hi @evoxmusic, do you have any update?

**Comment by sondrelg** [comment]
Would it be possible to handle the error by `continue`ing? [This](https://github.com/Qovery/Replibyte/blob/main/dump-parser/src/utils.rs#L74) is the relevant line, not the fixme. I can submit a PR if you could confirm @evoxmusic - I'm also affect by this

**Comment by evoxmusic** [comment]
Hi, yes can you provide a PR and I will adjust if needed

**Comment by sondrelg** [comment]
PR ready 🙂
