### ISSUE TITLE
Support Apple silicon mac?

### ISSUE THREAD

**Issue by ishikawa-pro** [Qovery/Replibyte#235]
Hi there.
I think I want to use the Replibyte on the M1 mac. but it seems to have released binary is x86_64-apple-darwin only.
Is there how to use the Replibyte on the Apple silicon mac?

and more, I tried to install the Replibyte from homebrew, I can launch it.
Can we use the x86 binary on the apple silicon mac?

**Comment by evoxmusic** [comment]
Hi, you can use the x86 binary on your M1 (I also have a M1 and it works fine). 

I didn't invest time to build an ARM version but it should works without any issue. Happy to have your contribution

**Comment by ishikawa-pro** [comment]
I also was able to dump and restore MongoDB's data on my M1 mac with x86 binary. 😄
Thank you for letting me know!
