### ISSUE TITLE
Feature: allow to add custom transformer

### ISSUE THREAD

**Issue by ThieryMichel** [Qovery/Replibyte#26]
Replibyte is great and really fast. Thanks for the good work.

I have a jsonb columns in my database with a user-defined format. And this column can hold sensitive information.
So I need to use custom logic to properly anonymize it.

Is it possible to add a transformer that would allow applying any custom transformation?
This transformer could call a user-defined bash command to transform the value.

**Comment by benny-n** [comment]
> However, one solution would be to create an extension system loading a custom transformer that could be written in any language compatible with Web Assembly and loading the Web Assembly module.

@evoxmusic  Can web assembly modules be loaded dynamically? 🤔
I'm not sure. 
If not, this would mean the user would have to rebuild RepliByte with wasm bindings each time he'd want to include a new web assembly module.

**Comment by evoxmusic** [comment]
There is a popular wasm runtime named "[wasmer](https://wasmer.io/)" that allow to load dynamically a wasm module. https://docs.wasmer.io/integrations/examples/instance#loading-the-wasm-module .

So no build needed. Just the build of the wasm module. Which is ok I guess :)

**Comment by benny-n** [comment]
> There is a popular wasm runtime named "[wasmer](https://wasmer.io/)" that allow to load dynamically a wasm module. 

Nice! that is definitely the way to go. If I'll have some extra time I'll start looking into this :)

**Comment by evoxmusic** [comment]
I can't wait to see what we can do with wasm. Definitely a good use case here.
