### ISSUE TITLE
Feature: restore in a local container for dev purpose

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#32]
Hey everyone 👋🏽  I have an idea that can make developer life so much easier while developing locally. What do you think of creating a command like this one 👇

```
$ replibyte restore -v latest --local
Restore complete!

To connect to your Postgres database, use the following connection string:
DATABASE_URL=postgres://root:password@localhost:5432/root
```

This command would start a local docker of the appropriate database (E.g Postgres) and restore the latest dump into it.

## Main benefits

Work locally with safe production data.

Happy to have your feedback.

**Comment by evoxmusic** [comment]
> I'm actually not sure how to stream the dump inside the container, maybe by running a docker exec CONTAINER psql ... command but I'm not sure It will works.

What could work is to:
1. Start the container and configure the network and credentials to be able to connect locally.
2. Wait for the container to be well started and check that the socket is open.
3. Then inject the dump into it.
4. Return the credentials to the user.

I think this way it's all good.

**Comment by LouGhys** [comment]
Really looking forward to this!
