### ISSUE TITLE
Release action fails for target `x86_64-apple-darwin`

### ISSUE THREAD

**Issue by benny-n** [Qovery/Replibyte#56]
Currently, the release action fails with this error:
>   = note: Undefined symbols for architecture x86_64:
            "_clock_gettime", referenced from:
                wasmer_wasi::syscalls::clock_time_get::haf582eb828a0fd26 in libwasmer_wasi-fc2597b33c106c49.rlib(wasmer_wasi-fc2597b33c106c49.wasmer_wasi.a26eec5f-cgu.0.rcgu.o)
            "_clock_getres", referenced from:
                wasmer_wasi::syscalls::clock_res_get::h24af0486cc9fc758 in libwasmer_wasi-fc2597b33c106c49.rlib(wasmer_wasi-fc2597b33c106c49.wasmer_wasi.a26eec5f-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang-12: error: linker command failed with exit code 1 (use -v to see invocation)

As mentioned [here](https://spectrum.chat/wasmer/general/compilation-error-on-os-x-10-11~360a0ab6-ddbe-4189-bc61-5baa5988f782), it looks like `clock_gettime` was only added in OSX 10.12.
Which means compiling for OSX 10.11 and earlier will fail.
 
The action we are currently using for our releases indeed [uses an earlier version (10.10)](https://github.com/rust-build/rust-build.action/blob/5923edc6a58fb59a59c0b90fef82667cd82b579c/Dockerfile#L24) for compilation.

What we can do next:

1. We can find a different github action for binary releases to use.
2.  We can open an issue for https://github.com/rust-build/rust-build.action, letting them know about the error and maybe ask them to update their build script.
3.  We can open an issue for https://github.com/wasmerio/wasmer, and if we're lucky they might come up with a clever solution which will remove the dependency of this API and make the error irrelevant.

@evoxmusic How would you like to procceed?

**Comment by evoxmusic** [comment]
What do you think is better? I have the feeling that all options have some pros and cons. (thanks a lot for investigating)

**Comment by benny-n** [comment]
Well I think we should try at least 1-2 other github actions before posting issues.

This [post](https://alican.codes/rust-github-actions) looks promising.

**Comment by benny-n** [comment]
@evoxmusic 
I think this one can be closed, the macOS build succeeds consistently now and it looks like the homebrew release succeeds as well 🙂

**Comment by evoxmusic** [comment]
🔥
