### ISSUE TITLE
Provide a delete backup command

### ISSUE THREAD

**Issue by fabriceclementz** [Qovery/replibyte#66]
Hi @evoxmusic 

Over the time, more and more backups adds up on the bridge so I think that would be good to have a command to delete a backup from the bridge. This is the signature I propose : 

```sh
replibyte -c "config.yml" backup delete "backup-name-here"
```

In the future we could add options to delete backups like `--older-than=14d` or so.

WDYT?

**Comment by evoxmusic** [comment]
Good idea. Plus, the `--older-than=14d` option is the most useful one. Or we can even think about an option like `--keep-last=10` to keep the last 10 backups.

**Comment by fabriceclementz** [comment]
👍  I will submit a PR
