### ISSUE TITLE
Set custom backup name

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#67]
As a user of RepliByte, I might want to choose the name of a backup with a better name than the one auto-generated. The option could be added during the run of `backup run` command.

```bash
replibyte -c conf.yaml backup run --name=my-backup-name
```

WDYT?

**Comment by fabriceclementz** [comment]
👍  It could be useful for people which use the same S3 bucket for many projects.
So you could name it with your project name. However, we should keep the timestamp suffix?  
For example, the final backup will be named `my-backup-name-1651170187000`. Are you ok with this?

**Comment by evoxmusic** [comment]
I am not sure if it is necessary, since you might want to restore a predictable name `replibyte restore -v my-backup-name`

**Comment by fabriceclementz** [comment]
I think you're right! 
It's simpler with a simple predictable name and it's simple enough to add a timestamp or what you want by scripting the backup with a simple bash or in crontab.
