### ISSUE TITLE
Create a Transformer to generate a first name

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/replibyte#8]
Create a transformer to generate a "first name" from a list.

### Example 1

Input: Romaric
Output: Julie

### Example 2

Input: Lucas
Output: Georges

### Example 3

Input: Etienne
Output: Julienne

### Example 4

Input: Null
Output: Null

### Example 5

Input: "" (empty)
Output: "" (empty)

### Example 6

Input: 123
Output: 123

**Comment by fabriceclementz** [comment]
Hi ! Thx for this project, It will be very helpful for me ! I will try to tackle this issue.

**Comment by evoxmusic** [comment]
Hey @fabriceclementz can you give more details about your use case?

**Comment by fabriceclementz** [comment]
For sure, I have some MySQL and Mongo production databases that I'll want to replicate on staging or other environments and I need to anonymize some fields during this process. So Replibyte seems to be the perfect tool for that !

**Comment by fabriceclementz** [comment]
This issue is solved by https://github.com/Qovery/replibyte/pull/12
