### ISSUE TITLE
Nomenclature / naming

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/Replibyte#80]
I have the feeling that "bridge" does not mean anything and it might be more accurate to rename it into something like "store". The idea is a place where to store the created dataset from the source database. A "bridge" does not really reflect this concept. What do you think?

**Comment by fabriceclementz** [comment]
It make sense to rename it to store. As you said, it's the place where backups are stored 👍 
I don't think "bridge" is a bad name either but "store" is conceptually more accurate to me.

**Comment by evoxmusic** [comment]
What do you think of datastore? (naming is definitely the most challenging part of any project 😂)

**Comment by fabriceclementz** [comment]
I can only agree, naming and cache invalidation 😄  Datastore is great too, maybe it's more common as it's more "specialized".  I even prefer it!

Backup store could be another alternative.

**Comment by evoxmusic** [comment]
Ahah, let's go for "datastore" then. 

BTW, I think we'll also need to rename "backup" and "restore" since it sounds very "backup tool". I don't have any idea yet on what it's more suitable to use. But my feeling is "backup" and "restore" can be confusing with a backup solution...

**Comment by benny-n** [comment]
"Datastore" sounds good 🙂 
I suggest renaming "backup" into "dump", since we use pg_dump/mongodump tools for it anyway, it seems like the most appropriate name for this command in my opinion.
As for "restore", I can't come up with a better name. 

Might be unrelated to this issue but I also think we should consider a "replicate" command (we are *Repli*Byte after all 😉)
This command should answer to a common use-case of simply replicating a production database into a local database, with one command.
i.e `replibyte -c conf.yaml replicate` would run backup with a transient bridge and restore into a local container.
What do you guys think?

**Comment by fabriceclementz** [comment]
+1 for dump, the only drawback of this name is that it doesn't express the fact we can transform data.
That said, I'm not sure we can find a better name than dump or backup.

For me, a command that restore directly to a local container without a "datastore" doesn't need to have another name. 
It's just a new "datastore" type (aka transient) that we could express in the config file.
But it will definitely be a great addition for some simple use cases. Maybe we should continue this discussion in another issue 🙂

**Comment by evoxmusic** [comment]
(we can keep chatting here)

I think `dump` is much better than `backup` since backup refers to the action of backing up the data of X to prevent data loss. Maybe we can use `dump` for an original dump, and `transformed dump` for the one modified by Replibyte.

```mermaid
flowchart LR
    dump --> transformer --> transformed-dump
```

The CLI commands would be something like: 

to create a dump
```bash
replibyte -c conf.yaml dump create ...
```

to restore it
```bash
replibyte -c conf.yaml dump restore
```

WDYT?

---

> Might be unrelated to this issue but I also think we should consider a "replicate" command (we are RepliByte after all 😉)
This command should answer to a common use-case of simply replicating a production database into a local database, with one command.
i.e replibyte -c conf.yaml replicate would run backup with a transient bridge and restore into a local container.
What do you guys think?

Ahah, "We are Replibyte" I love it 💪🏼

I do really like this use case because it's aligned with something we have in mind since the beginning. How can we smoothly move the data from database A to database B, regardless of where they are located. Maybe we can create another issue to talk about it?

**Comment by evoxmusic** [comment]
I think we can close this issue, I've renamed `backup` for `dump` and `bridge` for `datastore`. It looks clearer. If you see something wrong with the naming, you can re-open this issue. :)
