### ISSUE TITLE
Restore command doesn't keep column name quoted

### ISSUE THREAD

**Issue by 2Kable** [Qovery/Replibyte#81]
The current implementation of the restore command doesn't seem to keep the column name quoted:

Given a `Order` table with a `customerId` column, the pg_dump will correctly keep the column name quoted
But when running the restore command it will forward the sql command with column unquoted, leading pgsql, to look for the `customerid` column

EG:
The raw dump will contain:
```sql
INSERT INTO public.orders (id, "customerId") VALUES ....
```
While the restore command will send 
```sql
INSERT INTO public.orders (id, customerId) VALUES ....
```
leading to the following error
```
ERROR:  column "customerId" of relation "orders" does not exist
```

**Comment by evoxmusic** [comment]
Hi @2Kable , are you sure about the format of the `INSERT INTO...` query with the double quotes "customerId". I am not sure if it is a valid INSERT INTO query for PostgreSQL.

**Comment by evoxmusic** [comment]
I'll take a look ASAP to reproduce and provide a fix
