### ISSUE TITLE
Create official replibyte container image

### ISSUE THREAD

**Issue by wtait1-ff** [Qovery/Replibyte#97]
The [new documentation](https://www.replibyte.com/docs/guides/deploy-replibyte/container) for how to deploy / run `replibyte` as a container workload is great! But right now there are a bunch of steps on how to build a custom container image. It would be ideal to have some CI that builds and releases a standard `replibyte` container image that users can just download from some well-known, public registry.

Seeing as `replibyte` already uses Github Actions, it seems reasonable to create another GA workflow that builds and pushes an image to Github Container Registry. All the binary releases are [currently triggered when a Github release is created](https://github.com/Qovery/Replibyte/blob/101f86774e1c0895f0b459c7e23e40d715017191/.github/workflows/on-release.yml#L1-L5), so we can use the same trigger for the image build + push.

**Comment by evoxmusic** [comment]
It's a very good point. Do you want to bootstrap something? It will help a lot 🙂

**Comment by wtait1-ff** [comment]
Yep I'm happy to get a 1st iteration thrown together for this 🚀

**Comment by wtait1-ff** [comment]
Woooh the post-release image build [succeeded](https://github.com/Qovery/Replibyte/runs/6515745039?check_suite_focus=true#step:5:2586), and I see the repo lists 1 package - but I can't view it in Github or `docker pull` it.

My guess is the package was created with "private" visibility? In my test repo the package got created automatically with public visibility, so maybe there's some difference between packages for users vs. orgs (or maybe there's some setting enabled in the `Qovery` org to control this 🙂  )

**Comment by evoxmusic** [comment]
I can take a look

**Comment by evoxmusic** [comment]
And now?

**Comment by wtait1-ff** [comment]
```sh
> docker pull ghcr.io/qovery/replibyte:0.7.2
0.7.2: Pulling from qovery/replibyte
f003217c5aae: Already exists
332ccea85222: Already exists
a8de342c853a: Pull complete
5245b818ac03: Pull complete
af45f7874f5d: Pull complete
cfa6bb659a84: Pull complete
58ebed3b913a: Pull complete
Digest: sha256:e704c308ab587bd977630cc6841a2a3b8a2d8f11b3277fd1e8629d7423201c35
Status: Downloaded newer image for ghcr.io/qovery/replibyte:0.7.2
ghcr.io/qovery/replibyte:0.7.2
```

Looking good!! 🚀 🐳
