### ISSUE TITLE
Unable to process local dump file

### ISSUE THREAD

**Issue by chruzcruz** [Qovery/Replibyte#98]
Good Afternoon, 

I am trying to process a local dump file but unable to bypass the requirement for a valid connection_uri.

`
cat production.sql | replibyte -c conf.yaml dump create -i
`

Please see below for my configuration 
`source:
  connection_uri: "postgres://root:password@localhost:5453/root"
  transformers:
    - database: public
      table: table2
      columns:
        - name: city
          transformer_name: random
        - name: postal_code
          transformer_name: random
destination:
  # it's different to the source
  connection_uri: postgres://root:password@localhost:5453/root
datastore:
  gcp:
    bucket: xxx-db-xxx
    region: xxx
    access_key: xxxx
    secret: xxxx`

Setting Dummy placeholder
`command error: pg_dump: error: connection to server at "local.google.com" (172.217.165.14), port 5432 failed: Operation timed out
        Is the server running on that host and accepting TCP/IP connections?  
`
Not Setting value
`
thread 'main' panicked at 'bad config file format: Message("missing field `connection_uri`", Some(Pos { marker: Marker { index: 22, line: 2, col: 14 }, path: "source" }))', replibyte/src/main.rs:83:56
`

**Comment by fabriceclementz** [comment]
Hi @chruzcruz 

As a workaround, I suggest you add a fake connection_uri as the source connection uri is not optionnal for now and the `-s postgresql` flag to indicate the source database type.

So your command should be: `cat production.sql | replibyte -c conf.yaml dump create -i -s postgresql`

It should works. We're working on a fix.
